# Generated by Django 6.0.6 on 2026-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'dashboard_alertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'dashboard_resenas',
                'managed': False,
            },
        ),
    ]
